services:
  livox: 
    image: livox-ros-driver
    network_mode: host
    volumes: 
      - type: bind
        source: ./config
        target: /ros2/install/livox_ros_driver2/share/livox_ros_driver2/config/
    command: ["ros2", "launch", "livox_ros_driver2", "msg_MID360_launch.py"]