# optionally mirror configuration can be done by defining it as a registry.
[registry."128.16.29.85:5000"]
  http = true
  insecure = true

# optionally mirror configuration can be done by defining it as a registry.
[registry."127.0.0.1:5000"]
  http = true
  insecure = true
